---
- name: Deploy MongoDB
  hosts: mongodb
  become: True
  roles:
    - name: mongodb
  vars:
    mongodb_version: "4.4"

- name: Deploy Elasticsearch
  hosts: es
  roles:
    - name: elasticsearch
  vars:
    es_version: 7.10.2
    es_data_dirs:
      - "/opt/elasticsearch/data"
    es_log_dir: "/opt/elasticsearch/logs"
    es_config:
      node.name: "master-node"
      cluster.name: "my-cluster"
      discovery.seed_hosts: "localhost:9300"
      http.port: 9200
      transport.port: 9300
      node.data: False
      node.master: True
      bootstrap.memory_lock: True
    es_heap_size: 1g
    es_start_service: True
    es_api_port: 9200
    es_plugins:
      - plugin: ingest-attachment
