---
- name: Deploy MongoDB
  hosts: mongodb
  become: true 
  roles:
    - name: mongodb
  vars:
    mongodb_version: "4.4"

- name: Deploy Elasticsearch Master Nodes
  hosts: esmaster
  become: true
  roles:
    - name: elasticsearch
  vars:
    es_version: 7.10.2
    es_data_dirs:
      - "/opt/elasticsearch/data"
    es_log_dir: "/opt/elasticsearch/logs"
    es_config:
      cluster.name: "es-cluster"
      cluster.initial_master_nodes: "dev1.labk8s.pl"
      discovery.seed_hosts: "dev1.labk8s.pl:9300"
      http.host: 0.0.0.0
      http.port: 9200
      node.data: true
      node.master: true
      transport.host: 0.0.0.0
      transport.port: 9300
      bootstrap.memory_lock: false
    es_heap_size: 1g
    es_start_service: true
    es_plugins:
      - plugin: ingest-attachment

- name: Deploy Elasticserach Data Nodes
  hosts: esdata
  become: true
  roles:
    - name: elasticsearch
  vars:
    es_version: 7.10.2
    es_data_dirs:
      - "/opt/elasticsearch/data"
    es_log_dir: "/opt/elasticsearch/logs"
    es_config:
      cluster.name: "es-cluster"
      cluster.initial_master_nodes: "dev1.labk8s.pl"
      discovery.seed_hosts: "dev1.labk8s.pl:9300"
      http.host: 0.0.0.0
      http.port: 9200
      node.data: true
      node.master: false
      transport.host: 0.0.0.0
      transport.port: 9300
      bootstrap.memory_lock: false    
    es_heap_size: 1g
    es_start_service: true
    es_plugins:
      - plugin: ingest-attachment

- name: Deploy Graylog
  hosts: graylog
  become: true
  roles:
    - name: graylog
  vars:
    graylog_version: "4.1"
    graylog_elasticsearch_hosts: "http://dev1.labk8s.pl,http://dev2.labk8s.pl"
    graylog_mongodb_uri: "mongodb://dev3.labk8s.pl:27017/graylog"
