---
- name: mongodb
  src: https://github.com/kkurpanik/ansible-roles-mongodb.git
  version: main

- name: elasticsearch
  src: https://github.com/elastic/ansible-elasticsearch.git
  version: master

- name: graylog
  src: https://github.com/kkurpanik/ansible-roles-graylog.git
  version: main