---
- name: mongodb
  src: https://github.com/ansible-collections/community.mongodb.git
  version: 1.3.1

- name: elasticsearch
  src: https://github.com/elastic/ansible-elasticsearch.git
  version: v7.14.0

- name: nginx-proxy-role
  src: https://github.com/kkurpanik/ansible-roles-nginx-proxy.git
  version: 1.0.2
