---
- name: Install pip and setuptools (RedHat7)
  yum:
    name: "{{ item }}"
    state: present
  register: _pkg
  until: _pkg is succeeded
  retries: 5
  with_items:
    - epel-release
    - python-pip
    - python-setuptools
  when: ansible_facts['distribution_major_version'] == "7"

- name: Install pip and setuptools (RedHat8)
  yum:
    name: "{{ item }}"
    state: present
  register: _pkg
  until: _pkg is succeeded
  retries: 5
  with_items:
    - python3-pip
    - python3-setuptools
  when: ansible_facts['distribution_major_version'] == "8"
