---
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    box: ${MOLECULE_DISTRO:-generic/ubuntu2004}
    memory: 4096
    cpu: 1
provisioner:
  name: ansible
verifier:
  name: testinfra
  options:
    s: true
