---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider: 
    name: libvirt
    type: libvirt
  parallel: true
lint: |
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: centos7
    box: centos/7
    memory: 8192
    cpus: 2
  - name: centos8
    box: centos/8
    memory: 8192
    cpus: 2
  - name: debian11
    box: debian/bullseye64
    memory: 8192
    cpus: 2
provisioner:
  name: ansible
verifier:
  name: testinfra
  options:
    s: true
